local_backend: true

backend:
  name: git-gateway
  branch: master

media_folder: static/images/blog
public_folder: /images/blog

media_library:
  name: cloudinary
  output_filename_only: false
  config:
    cloud_name: planer-osobisty
    api_key: 458159627694677
    default_transformations:
      - - fetch_format: auto
          width: 1400
          quality: auto
          crop: scale

publish_mode: editorial_workflow

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    format: 'frontmatter'
    create: true
    slug: '{{short_name}}'
    preview_path: 'blog/{{short_name}}'
    editor:
      preview: true
    fields:
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Short name'
        name: 'short_name'
        widget: 'string'
      - label: 'Thumbnail'
        name: 'thumbnail'
        widget: 'image'
        default: 'thumbnail'
        media_library:
          config:
            multiple: false
      - label: 'Publish Date'
        name: 'date'
        widget: 'datetime'
      - label: 'Description'
        name: 'description'
        widget: 'string'
        hint: 'Between 50-160 characters (https://www.charactercountonline.com/)'
        pattern: ['.{50,160}', "Must have between 50 and 160 characters"]
      - label: 'Body'
        name: 'body'
        widget: 'markdown'
      - label: 'List'
        name: 'list'
        widget: 'list'
        fields:
          - {label: Thumbnail, name: 'ttt', widget: 'image'}

